---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yourusername/public_html/telegram_bot
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -rf * $DEPLOYPATH
    - /bin/cp -rf .[^.]* $DEPLOYPATH 2>/dev/null || /bin/true
    - /bin/touch $DEPLOYPATH/passenger_wsgi.py
    - /bin/touch $DEPLOYPATH/passenger_wsgi.py.bak
    - /usr/bin/find $DEPLOYPATH \( -name .git -o -name .cpanel.yml \) -exec /bin/rm -rf {} \; 2>/dev/null
    - /usr/local/cpanel/3rdparty/bin/git --git-dir=$DEPLOYPATH/.git --work-tree=$DEPLOYPATH checkout --force
    - /bin/echo "Deployment complete."
