name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
      - name: fetching secret keys 
        env:
          AKI_MONGO_HOST: ${{ secrets.AKI_MONGO_HOST }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_TELEGRAM_USER_ID: ${{ secrets.ADMIN_TELEGRAM_USER_ID }}
          PUBLIC_CHANNEL_USERNAME: ${{ secrets.PUBLIC_CHANNEL_USERNAME}}
